### ISSUE TITLE
Cannot understand how to use it

### ISSUE THREAD

**Issue by ugnelis** [eddyxu/cpp-coveralls#125]
I was reading cpp-coveralls README.md example but couldn't understand `./configure --enable-gcov`. Is `configure `a built file by cmake? 

Cheers!

**Comment by mkfifo** [comment]
No, that line in the documentation just means "run your app however you would usually run it but make sure to enable gcov"

Here is a config of mine for a project I wrote which does not use ./configure but instead uses just make
https://github.com/mkfifo/icarus/blob/master/.travis.yml

this works because my make test always compiles with gcov
https://github.com/mkfifo/icarus/blob/master/config.mk#L13
https://github.com/mkfifo/icarus/blob/master/Makefile#L28

So for your application all you need to do it make sure you compile and run with gcov enabled, have cpp-coveralls install, and then run cpp coveralls at the end to upload results

```
language: cpp
compiler:
  - gcc
before_install:
  - pip install --user cpp-coveralls
script:
  - echo "do whatever you want in here to build and run your application/test"
  - echo "just make sure that you compile with gcov options"
  - echo "for gcc this means using the flags `-fprofile-arcs -ftest-coverage`"
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
```

**Comment by ugnelis** [comment]
Yesterday I have achieved to do a bit differently. Maybe do you know why I am getting 100% coverages on the files which don't have tests?

**Comment by mkfifo** [comment]
The coverage is calculated by whatever code you *run* with gcov enabled, not just what you test.
So whatever you have executed before you run cpp-coveralls will be included.

But without seeing your config I can't be expected to debug it.

**Comment by ugnelis** [comment]
Thanks, I have solved the problem
